name: Upload Artifact
on: 
  push:
    branches:
      - dev
jobs:
  build:
    name: Create
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p /home/runner/artifact
      - run: echo hello > /home/runner/artifact/world.txt
      - run: tar zcvf artifact.tar.gz /home/runner/artifact
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /home/runner/artifact.tar.gz
